backend:
  name: git-gateway
  branch: master
media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "static/img"
collections:
  -   name: "pages"
      label: "Seitenübersicht"
      files:
      - file: "content/_index.md"
        label: "Homepage"
        name: "home"
        editor:
          preview: true
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Seitentext", name: "body", widget: "markdown" }
          
      - file: "content/impressum.md"
        label: "Impressum"
        name: "impressum"
        editor: 
          preview: true
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Seitentext", name: "body", widget: "markdown" } 
      - file: "content/kontakt.md"
        label: "Kontakt"
        name: "kontakt"
        editor: 
          preview: true
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Seitentext", name: "body", widget: "markdown" }
      - file: "content/kurse-aktuelles.md"
        label: "Kurse aktuelles"
        name: "kurse-aktuelles"
        editor: 
          preview: true
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - label: "Kurse-aktuelles"
            name: "inhalt" 
            widget: "list" 
            summary: '{{fields.headline}}' 
            fields:
             - { label: "Beschreibung", name: "headline", widget: "string" }  
             - { label: "Textinhalt", name: "textArea", widget: "string" } 
      - file: "content/praxis.md"
        label: "Praxis"
        name: "praxis"
        editor: 
          preview: true
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Seitentext", name: "body", widget: "markdown" }
      - file: "content/über-mich.md"
        label: "Über mich"
        name: "überm-ich"
        editor: 
          preview: true
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Seitentext", name: "body", widget: "markdown" } 
      